"""uuid, place extend, person search, audit_log

Revision ID: 528e42e57fa9
Revises: f6719a00a292
Create Date: 2026-08-03 01:48:13.534172

"""
from alembic import op
import sqlalchemy as sa
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = '528e42e57fa9'
down_revision = 'f6719a00a292'
branch_labels = None
depends_on = None

# Taules existents a les quals s'afegeix el columna `uuid`.
_TABLES_WITH_UUID = ["persons", "families", "places", "events", "sources",
                     "media", "suggestions"]


def _backfill_uuid(table: str) -> None:
    """Omple el camp `uuid` de files existents amb UUID v4 únic.

    SQLite no genera UUIDs a la capa de servidor; cal assignar-los des de
    Python perquè la columna `uuid` (NOT NULL + UNIQUE) sigui vàlida sobre
    una taula amb dades.
    """
    connection = op.get_bind()
    rows = connection.execute(sa.text(f"SELECT id FROM {table}")).fetchall()
    for (row_id,) in rows:
        connection.execute(
            sa.text(f"UPDATE {table} SET uuid = :u WHERE id = :rid"),
            {"u": str(uuid4()), "rid": row_id},
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic (manually adjusted) ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='person | family | place | event | ...'),
    sa.Column('entity_id', sa.String(length=255), nullable=False, comment='UUID o id enter de la entitat afectada'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='create | update | delete | import | ...'),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True, comment="Canvis o metadades de l'accio (JSON serialitzat)"),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Identificador públic (UUID v4) per API i sincronització'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=True)

    # Afegim `uuid` com a NULLABLE a les taules existents...
    op.add_column('events', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('families', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('media', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('persons', sa.Column('search_name', sa.String(length=511), nullable=True, comment='Concatenacio nom + cognoms per a la cerca full-text'))
    op.add_column('persons', sa.Column('slug', sa.String(length=120), nullable=True, comment='Slug url-friendly de la persona'))
    op.add_column('persons', sa.Column('soundex', sa.String(length=4), nullable=True, comment='Codigo fonetico Soundex del cognom (preparat; no usat encara)'))
    op.add_column('persons', sa.Column('metaphone', sa.String(length=255), nullable=True, comment='Codigo fonetico metaphone (preparat; integracio futura)'))
    op.add_column('persons', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('places', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('places', sa.Column('canonical_name', sa.String(length=255), nullable=True))
    op.add_column('places', sa.Column('country', sa.String(length=120), nullable=True))
    op.add_column('places', sa.Column('region', sa.String(length=120), nullable=True))
    op.add_column('places', sa.Column('province', sa.String(length=120), nullable=True))
    op.add_column('places', sa.Column('municipality', sa.String(length=120), nullable=True))
    op.add_column('places', sa.Column('geohash', sa.String(length=12), nullable=True))
    op.add_column('places', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('places', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('sources', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))
    op.add_column('suggestions', sa.Column('uuid', sa.String(length=36), nullable=True, comment='Identificador públic (UUID v4) per API i sincronització'))

    # ...i les emplenem amb UUIDs únics per a les files ja existents.
    for table in _TABLES_WITH_UUID:
        _backfill_uuid(table)

    # Creem els índexs únics un cop tota fila té un uuid vàlid.
    op.create_index(op.f('ix_events_uuid'), 'events', ['uuid'], unique=True)
    op.create_index(op.f('ix_families_uuid'), 'families', ['uuid'], unique=True)
    op.create_index(op.f('ix_media_uuid'), 'media', ['uuid'], unique=True)
    op.create_index(op.f('ix_persons_search_name'), 'persons', ['search_name'], unique=False)
    op.create_index(op.f('ix_persons_slug'), 'persons', ['slug'], unique=False)
    op.create_index(op.f('ix_persons_soundex'), 'persons', ['soundex'], unique=False)
    op.create_index(op.f('ix_persons_uuid'), 'persons', ['uuid'], unique=True)
    op.create_index('ix_places_canonical_name', 'places', ['canonical_name'], unique=False)
    op.create_index('ix_places_geohash', 'places', ['geohash'], unique=False)
    op.create_index('ix_places_slug', 'places', ['slug'], unique=False)
    op.create_index(op.f('ix_places_uuid'), 'places', ['uuid'], unique=True)
    op.create_index(op.f('ix_sources_uuid'), 'sources', ['uuid'], unique=True)
    op.create_index(op.f('ix_suggestions_uuid'), 'suggestions', ['uuid'], unique=True)

    # Apliquem NOT NULL a `uuid` de les taules exist. SQLite ho exigeix
    # amb una recreació de taula; aleatoriSetup amb ALTER per simpletat
    # es manté NULL-able però sempre ple a l'app (default client-side).
    # Per a consistència estricta, es deixa documentat; en aquest sprint
    # la integritat es garanteix a la capa d'aplicació.


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic (manif insert) ###
    op.drop_index(op.f('ix_suggestions_uuid'), table_name='suggestions')
    op.drop_column('suggestions', 'uuid')
    op.drop_index(op.f('ix_sources_uuid'), table_name='sources')
    op.drop_column('sources', 'uuid')
    op.drop_index(op.f('ix_places_uuid'), table_name='places')
    op.drop_index('ix_places_slug', table_name='places')
    op.drop_index('ix_places_geohash', table_name='places')
    op.drop_index('ix_places_canonical_name', table_name='places')
    op.drop_column('places', 'uuid')
    op.drop_column('places', 'slug')
    op.drop_column('places', 'geohash')
    op.drop_column('places', 'municipality')
    op.drop_column('places', 'province')
    op.drop_column('places', 'region')
    op.drop_column('places', 'country')
    op.drop_column('places', 'canonical_name')
    op.drop_column('places', 'display_name')
    op.drop_index(op.f('ix_persons_uuid'), table_name='persons')
    op.drop_index(op.f('ix_persons_soundex'), table_name='persons')
    op.drop_index(op.f('ix_persons_slug'), table_name='persons')
    op.drop_index(op.f('ix_persons_search_name'), table_name='persons')
    op.drop_column('persons', 'uuid')
    op.drop_column('persons', 'metaphone')
    op.drop_column('persons', 'soundex')
    op.drop_column('persons', 'slug')
    op.drop_column('persons', 'search_name')
    op.drop_index(op.f('ix_media_uuid'), table_name='media')
    op.drop_column('media', 'uuid')
    op.drop_index(op.f('ix_families_uuid'), table_name='families')
    op.drop_column('families', 'uuid')
    op.drop_index(op.f('ix_events_uuid'), table_name='events')
    op.drop_column('events', 'uuid')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###