"""afegir dates normalitzades i xref sources/media

Revision ID: f6719a00a292
Revises: 8a23be0107a8
Create Date: 2026-08-02 23:26:30.452571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6719a00a292'
down_revision = '8a23be0107a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_iso', sa.String(length=10), nullable=True))
    op.add_column('events', sa.Column('date_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_date_iso'), 'events', ['date_iso'], unique=False)
    op.create_index(op.f('ix_events_date_year'), 'events', ['date_year'], unique=False)
    op.add_column('media', sa.Column('xref', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_media_xref'), 'media', ['xref'], unique=False)
    op.add_column('sources', sa.Column('xref', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_sources_xref'), 'sources', ['xref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_xref'), table_name='sources')
    op.drop_column('sources', 'xref')
    op.drop_index(op.f('ix_media_xref'), table_name='media')
    op.drop_column('media', 'xref')
    op.drop_index(op.f('ix_events_date_year'), table_name='events')
    op.drop_index(op.f('ix_events_date_iso'), table_name='events')
    op.drop_column('events', 'date_year')
    op.drop_column('events', 'date_iso')
    # ### end Alembic commands ###